server:
  servlet:
    context-path: /intraway/api
  port: 8090

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=intraway
    username: user
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver